### ISSUE TITLE
Doubts about implementation

### ISSUE THREAD

**Issue by HackNick2018** [spectresystems/jarvis#12]
# Information for developers
### I would like to obtain information about the IDE's used for the implementation of this project. Thanks

**Comment by patriksvensson** [comment]
Not sure what you mean. Could you clarify?

**Comment by HackNick2018** [comment]
Of course!
For example : 
*Languajes*: C++,Shell
*IDE'S*: Visual Studio

**Comment by patriksvensson** [comment]
Languages: C#, PowerShell, Cake, WiX
IDE: Visual Studio 2017
