### ISSUE TITLE
Comparison to Wox Launcher

### ISSUE THREAD

**Issue by Meir017** [spectresystems/jarvis#15]
How does this product differentiate from [Wox](https://github.com/Wox-launcher/Wox)? They are both described as an alternative to [Alfred](https://www.alfredapp.com/)

**Comment by patriksvensson** [comment]
Because they both are alternatives to Alfred on Windows. I don’t know much about WoX but feel free to add comparison here 😊

**Comment by Meir017** [comment]
I just tested it and I found a really neat feature in the google addin, it shows the google suggestions.
I tried Wox a few months ago, It had a google adding that basically was a shortcut for searching in google.

This feature is amazing

**Comment by patriksvensson** [comment]
@Meir017 Thanks! 😄
