### ISSUE TITLE
Migrate to new csproj?

### ISSUE THREAD

**Issue by pardahlman** [spectresystems/jarvis#20]
Hej 😉

Great work with this project 👍 . Quick question, as it is probably me missing some aspect of the application, but here goes: any particular reason that the projects uses full framework csprojs (the _Windows Classic Desktop_)? I can see how the WPF parts needs .NET Framework, but I think it makes sense for addins (and possibly other libraries) to target .NET Standard.

**Comment by patriksvensson** [comment]
Not sure what the benefit would be to make addins netstandard to be honest except the new project format since addins both have COM dependencies and references to full FX assemblies such as PresentationCore. I’d rather wait for the new project format to come to WPF.

**Comment by pardahlman** [comment]
I think the new format is a benefit in itself! It is easier to work with (edit proj without unloading first, possibly avoid merge conflicts in csproj, interact with proj through `dotnet` CLI etc). From what I gather, Jarvis will not be a cross platform application, but that does not mean that it can't use the new goodness for .NET. Theoretically, .NET developers on non-Windows environment are unable to contribute to this project (which arguably aren't that many, but I'm on Windows and mac😜).

It is just a thought, feel free to close this issue if you're not convinced.

**Comment by patriksvensson** [comment]
I see no immediate benefit for this so I'm going to close it for now. Let's reopen it in the future if we decide to upgrade the project file format.
