### ISSUE TITLE
Consider remove fallback from Query signature

### ISSUE THREAD

**Issue by pardahlman** [spectresystems/jarvis#21]
Hello again 👋 ,

I was looking through the code and stumbled upon `IQueryProvider` and the signature

```chsarp
Task<IEnumerable<IQueryResult>> Query(Query query, bool fallback);
```

It was not immediately clear to me what `fallback` was in this context so I started to dig around. It looks like it is used in the following code block

```csharp
var result = (await provider.Query(query, false)).ToArray();
if (result.Length == 0)
{
    result = (await provider.Query(query, true)).ToArray();
}
```

So basically, the same method gets called again with `fallback` set to `true` if the provider was unable to provide any results. The provider itself knows if it didn't find any results and code provide the fallback _if it is able to do so_. There are scenarios where a provider does not have a reasonable fallback result (like the `FileProvider`). IMHO the `fallback` argument adds unnecessary complexity, as it is [magic bool](https://blog.codinghorror.com/avoiding-booleans/) that adds little value.

My suggestion is to remove the fallback argument and let the providers supply fallback when/if applicable. This would also simplify the interface as well as the logic in the call site (as it wouldn't need to check length of result etc).

Feel free to tell my why this is a stupid idea 😆

**Comment by patriksvensson** [comment]
You’re absolutely right about this 👍

**Comment by pardahlman** [comment]
Alright, do you want me to do a PR or would you rather fix this yourself?

**Comment by pardahlman** [comment]
Two more questions on the same theme:

* Is there any particular reason the signature does not take a `CancellationToken` as an optional argument?
* I was a bit surprised that the method was async, since [the guidelines for async programming](https://docs.microsoft.com/en-us/dotnet/csharp/async) suggests to suffix the method with `Async`. Is this a mistake or by design?

**Comment by patriksvensson** [comment]
Feel free to make a PR for this 👍
Won’t be around to make a review for a couple of days since I’m currently visiting my parents in law.

Feel free to add the Async suffix.
