### ISSUE TITLE
High idle memory usage

### ISSUE THREAD

**Issue by MisterJimson** [spectresystems/jarvis#27]
Using Jarvis for a few days.  Noticed it is constantly at 1gb+ of memory usage while idle.

Is this expected? Known issue?

**Comment by patriksvensson** [comment]
Hmm, that is not expected at all. I’ve been running it for a long time and it stays at around 90Mb for me. I might have introduced a memory leak somewhere though.

Would you mind sharing your log file in a gist?

**Comment by patriksvensson** [comment]
The log file should be in `C:/Users/AppData/Roaming/Jarvis/Logs`. I’m mostly interested in the trie information (number of nodes) etc.

**Comment by MisterJimson** [comment]
It went up to 2gb recently and now back to 1gb.

https://gist.github.com/MisterJimson/5fa9982a7c1e3d57a7afeee7cda7d607

https://gist.github.com/MisterJimson/555d7fd6b85481766d6a889b577352fa

**Comment by patriksvensson** [comment]
Ok, seems like we’re indexing a lot of data. Right now we index everything in memory and you seem to have a lot of files in your user folder. We should probably start being mor epicly about what we index or index to disk.

**Comment by MisterJimson** [comment]
Makes sense.

500,177 Files, 84,859 Folders, 92.3 GB is in my user folder.

**Comment by oskaremil** [comment]
Exclude folders would be a must. As a developer I have several projects with a node_modules folder. Each folder contains half the internet and 100000000 files :-/

**Comment by granttrevor** [comment]
> 3GB here at idle.

![image](https://user-images.githubusercontent.com/17581063/35489974-ce547316-04e7-11e8-8cca-eb699cd4db71.png)

**Comment by patriksvensson** [comment]
@granttrevor Have you tried excluding items that are not of interest to you?
