### ISSUE TITLE
Discussion: score and distance

### ISSUE THREAD

**Issue by pardahlman** [spectresystems/jarvis#40]
The `IQueryResult` has properties for `Score` and `Distance`. These are calculated and displayed for each result.

My first though is: _Is this really something that interests the end user?_. I'm not sure that a typical Jarvis users (or Addin developer for that matter 😉) know of Levenshtein or understand the difference between score and distance. Furthermore, sites like Google are experts at guessing what the user means even if it is way off. I would argue that their algorithms are more accurate and that in some scenarios the distance/score will not reflect the actual relevance?

What are your thoughts on this?

**Comment by patriksvensson** [comment]
Score and distance is only displayed in the debug build of Jarvis.

**Comment by pardahlman** [comment]
Aah, I didn't know that. I guess my question is then: why do we have score and distance 😄. Don't get me wrong, but to my knowledge it is not used for sorting the result and it is not shown to the end user and it is a concept that third party developers might find trick to grasp. Or am I wrong 🤔?

**Comment by patriksvensson** [comment]
@pardahlman Sorry for short answer, currently on my phone. Score is used for sorting the final aggregated result. Score is normalized levenstein distance and distance is levenstein distance. Distance is only interesting when debugging search results since it’s not normalized.

**Comment by pardahlman** [comment]
@patriksvensson - understood, and it makes sense when querying multiple providers. _However_, consider a Google query (only one provider). This query might produce results that are suggestions of a different, but similar, search phrases (right?) that Google ranks high. It would do poorly according to the Levenstein Score algorithm, and as a result be moved down?
