### ISSUE TITLE
Exclude folders

### ISSUE THREAD

**Issue by oskaremil** [spectresystems/jarvis#43]
I would like to have an option to exclude a set of folders from indexing.

**Comment by patriksvensson** [comment]
Relates to #27

**Comment by patriksvensson** [comment]
UI is hard 😢 but this is what it initially will look like.
We can interate over the final design of this once 0.7.0 is out.

![image](https://user-images.githubusercontent.com/357872/34801945-71a6dd50-f66b-11e7-8b0d-db836e53e60b.png)

**Comment by patriksvensson** [comment]
@oskaremil Will something like this work? https://github.com/spectresystems/jarvis/pull/47

**Comment by erkantaylan** [comment]
Can you add some options like 
```
[x] Exclute system files and folders
[ ] Exclude hidden files and folders
```
