### ISSUE TITLE
Crashes with no info if hotkey is already registered

### ISSUE THREAD

**Issue by dracan** [spectresystems/jarvis#45]
I was already using Wox when I installed this, and Jarvis just closed itself silently rather than telling me that something else was already using the hotkey. Jarvis worked fine after closing Wox.

**Comment by patriksvensson** [comment]
Thanks for reporting this. This will be fixed as part of 0.7.0 where we will move away from hot keys to a global keyboard hook, and also make the activation keys configurable.
