### ISSUE TITLE
Jarvis ownership and roadmap?

### ISSUE THREAD

**Issue by pardahlman** [spectresystems/jarvis#63]
Top of the morning, @patriksvensson ☕️

I think Jarvis has potential, but I'm wondering a bit about the roadmap and overship of the product. 

Many successful open source projects are typically owned by a (Github) organization that represents the project itself. Looking at Serilog as an example, [it's organization](https://github.com/orgs/serilog/people) contains OSS developers that been involved in the project. This is great for the project, as the workload can be shared among the members, members feels a responsibility for the project etc.

If I understand things correctly, _Spectre Systems AB_ is your one-man consulting firm. If that's the case then it makes sense that you don't want open source contributors to join your company's organization (that is conceptually awkward), and I believe it wouldn't feel right for the contributor either. With the current setup, you are the focal point in the project, and its progress is depend on how much time you can commit to it.

Looking at myself, I would feel better putting in hours in this project if:
* The repo was owned by an organization representing Jarvis
* If the file headers would read _Licensed to Jarvis Contributers_ (again similar to what [Serilog does](https://github.com/serilog/serilog/blob/dev/src/Serilog/Enrichers/LogContextEnricher.cs#L1)

Now, I can think of a few reasons why you still want Jarvis to be owned by your company... Anyways, looking forward hearing your thoungs!

**Comment by patriksvensson** [comment]
@pardahlman Let me try answering your questions.

Jarvis was created as a project at Spectre Systems AB, where I've actually taken time off from my regular work (about a day a week) to work on things I want to pursue personally. Spectre Systems is committed to supporting the project long-term and Jarvis (except the icon) is also licensed under the very permissive MIT license.

I do appreciate your honesty, but whether this is a one man shop currently is inconsequential in the long term as we can easily migrate it to an organization later if the need would arise. That won't however change the license owners. Adding maintainers to a repository is also possible as far as i know.

I totally understand if that means you won't contribute, but in the end that's your decision. Although, I hope you will.

Best regards
Patrik

**Comment by pardahlman** [comment]
In some sense, every hour spent on OSS could be an hour spent doing something else (that might generate revenue) 😉. Thanks for clarifying your position, I respect that and will take that into account when deciding where to put open source efforts.

Keep up the good job!
Pär
