### ISSUE TITLE
Indexing failed

### ISSUE THREAD

**Issue by grumpydev** [spectresystems/jarvis#66]
Last thing in the logs was:

Could not get stream for 'C:/Windows/SystemApps/Microsoft.BioEnrollment_cw5n1h2txyewy/AppxManifest.xml'.

[ServiceOrchestrator] File indexing service: One or more errors occurred. (System.AggregateException)

Delete the logs and restarted and everything seems fine. Only thing I had done prior to that was upgade, then change the settings to add some additional folders (Dropbox in my case), but it didn't seem to have indexed those at all looking at the logs, but indexed them all fine on restart.

**Comment by thecodejunkie** [comment]
I experienced this as well after upgrading from `0.5.0` to `0.8.0`. After restarting Jarvis (did not have to delete the logs) it started working again

My upgrade procedure was

- Close Jarvis 0.5.0
- Install 0.8.0
- Launch Jarvis
