### ISSUE TITLE
How to use Jarvis?

### ISSUE THREAD

**Issue by filipesilva** [spectresystems/jarvis#71]
Heya, I'm sorry if this is a stupid question but... how do I actually use Jarvis? 

I've downloaded the installer from releases page in github, then ran it to install Jarvis. Now my start menu shows Jarvis in the recently added. When I click on it I see a prompt saying "Jarvis is already running".

I don't know how to bring Jarvis up though. I guess there's a hotkey but it doesn't seem to be in the readme. This repository doesn't seem to have a wiki, and a cursory search in the issues doesn't seem to have anyone else asking the same.

I must be missing something... can someone tell me the hotkey please?

**Comment by patriksvensson** [comment]
The hotkeys are Alt+Space.

**Comment by filipesilva** [comment]
Thanks! Added a PR with that information in https://github.com/spectresystems/jarvis/pull/72.
