### ISSUE TITLE
Google search should always return exact search

### ISSUE THREAD

**Issue by patriksvensson** [spectresystems/jarvis#8]
If no result is returned, add an option to open the default browser with the entered query.

**Comment by jonstodle** [comment]
I can have a look at this tonight, I think.

**Comment by patriksvensson** [comment]
@jonstodle Perfect.

Btw, haven't forgot about your (or @pardahlman's) PR:s. Just super swamped with work and alone with daughter this week.

**Comment by jonstodle** [comment]
No stress. Sounds like you've got your priorities in order 👍

**Comment by patriksvensson** [comment]
This have already been resolved but forgot to close issue...

**Comment by agg23** [comment]
This appears to have regressed.

<img width="450" alt="Jarvis_2019-12-25_10-38-53" src="https://user-images.githubusercontent.com/238679/71449517-ce226580-2702-11ea-91e0-e5ae71d9adb9.png">
