### ISSUE TITLE
url open while added .com or other domain

### ISSUE THREAD

**Issue by dchmurec** [spectresystems/jarvis#93]
Hello,

is it possible to do like it is in Alfred when you write an URL and add at the end a domain, for example, spotify.com then its automatically open the website, here I see that this is also possible, but you have to add G before starting to search something.

**Comment by patriksvensson** [comment]
@haitashe That's part of the search engine provider, so you will need to type `G` (or `g`) before the URL.

**Comment by agg23** [comment]
Why is this specific to the search engine provider? Seems like direct URL navigation should be provided elsewhere (preferably globally).
